Add draft of article [deploy]

diff --git a/docs/bin/deploy b/docs/bin/deploy
--- a/docs/bin/deploy
+++ b/docs/bin/deploy
@@ -4,95 +4,102 @@
 
 # Parse cmd arguments
 
-SRC_BRANCH="master"
-DEPLOY_BRANCH="gh-pages"
 
-USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH]"
+bundle exec jekyll build --destination docs
+git add docs/
+git commit --allow-empty -m "$(git log -1 --pretty=%B) [deploy]"
+git push -f -q origin master
 
-while [[ $# > 0 ]]; do
-    key="$1"
 
-    case $key in
-        -h|--help)
-        echo $USAGE_MSG
-        exit 0
-        ;;
-        -u|--user)
-        SRC_BRANCH="source"
-        DEPLOY_BRANCH="master"
-        shift
-        ;;
-        -s|--src)
-        SRC_BRANCH="$2"
-        shift
-        ;;
-        -d|--deploy)
-        DEPLOY_BRANCH="$2"
-        shift
-        ;;
-        *)
-        echo "Option $1 is unknown."
-        echo $USAGE_MSG
-        exit 0
-        ;;
-    esac
-    shift
-done
+# SRC_BRANCH="master"
+# DEPLOY_BRANCH="gh-pages"
 
-# Exit if any subcommand fails
-set -e
+# USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH]"
 
-echo "Deploying..."
-echo "Source branch: $SRC_BRANCH"
-echo "Deploy branch: $DEPLOY_BRANCH"
+# while [[ $# > 0 ]]; do
+#     key="$1"
 
-read -r -p "Do you want to proceed? [y/N] " response
-if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
-then
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
-fi
+#     case $key in
+#         -h|--help)
+#         echo $USAGE_MSG
+#         exit 0
+#         ;;
+#         -u|--user)
+#         SRC_BRANCH="source"
+#         DEPLOY_BRANCH="master"
+#         shift
+#         ;;
+#         -s|--src)
+#         SRC_BRANCH="$2"
+#         shift
+#         ;;
+#         -d|--deploy)
+#         DEPLOY_BRANCH="$2"
+#         shift
+#         ;;
+#         *)
+#         echo "Option $1 is unknown."
+#         echo $USAGE_MSG
+#         exit 0
+#         ;;
+#     esac
+#     shift
+# done
 
-# Check if there are any uncommitted changes
-if ! git diff-index --quiet HEAD --; then
-    echo "Changes to the following files are uncommitted:"
-    git diff-index --name-only HEAD --
-    echo "Please commit the changes before proceeding."
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
-fi
+# # Exit if any subcommand fails
+# set -e
 
-# Switch to source branch (creates it if necessary from the current branch)
-if [ `git branch | grep $SRC_BRANCH | tr ' ' '\n' | tail -1` ]
-then
-    git checkout $SRC_BRANCH
-else
-    git checkout -b $SRC_BRANCH
-fi
+# echo "Deploying..."
+# echo "Source branch: $SRC_BRANCH"
+# echo "Deploy branch: $DEPLOY_BRANCH"
 
-# Checkout DEPLOY_BRANCH branch
-if [ `git branch | grep $DEPLOY_BRANCH` ]
-then
-  git branch -D $DEPLOY_BRANCH
-fi
-git checkout -b $DEPLOY_BRANCH
+# read -r -p "Do you want to proceed? [y/N] " response
+# if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
+# then
+#     echo "Aborting."
+#     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+# fi
 
-# Build site
-bundle exec jekyll build
+# # Check if there are any uncommitted changes
+# if ! git diff-index --quiet HEAD --; then
+#     echo "Changes to the following files are uncommitted:"
+#     git diff-index --name-only HEAD --
+#     echo "Please commit the changes before proceeding."
+#     echo "Aborting."
+#     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+# fi
 
-# Delete and move files
-find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name 'CNAME' ! -name '.gitignore' -exec rm -rf {} \;
-mv _site/* .
-rm -R _site/
+# # Switch to source branch (creates it if necessary from the current branch)
+# if [ `git branch | grep $SRC_BRANCH | tr ' ' '\n' | tail -1` ]
+# then
+#     git checkout $SRC_BRANCH
+# else
+#     git checkout -b $SRC_BRANCH
+# fi
 
-# Push to DEPLOY_BRANCH
-git add -fA
-git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
-git push -f -q origin $DEPLOY_BRANCH
+# # Checkout DEPLOY_BRANCH branch
+# if [ `git branch | grep $DEPLOY_BRANCH` ]
+# then
+#   git branch -D $DEPLOY_BRANCH
+# fi
+# git checkout -b $DEPLOY_BRANCH
 
-# Move back to SRC_BRANCH
-git checkout $SRC_BRANCH
+# # Build site
+# bundle exec jekyll build
 
-echo "Deployed successfully!"
+# # Delete and move files
+# find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name 'CNAME' ! -name '.gitignore' -exec rm -rf {} \;
+# mv _site/* .
+# rm -R _site/
 
-exit 0
+# # Push to DEPLOY_BRANCH
+# git add -fA
+# git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
+# git push -f -q origin $DEPLOY_BRANCH
+
+# # Move back to SRC_BRANCH
+# git checkout $SRC_BRANCH
+
+# echo "Deployed successfully!"
+
+# exit 0
